runtime: python27
api_version: 1
threadsafe: true

libraries:
  - name: webapp2
    version: latest
  - name: jinja2
    version: latest

handlers:
  - url: /favicon.ico
    static_dir: images/favicon.ico

  - url: /scripts
    static_dir: scripts

  - url: /stylesheets
    static_dir: stylesheets

  - url: /.*
    script: ganban.app
